### ISSUE TITLE
Convert ZED Depth Image to Laser Scan

### ISSUE THREAD

**Issue by wraftus** [uwreact/uwreact_robot#68]
# 🚀 Feature Request

The AMCL node takes in a laser scan to figure out where the robot is, so we need to convert our zed depth image into the laser scan format it wants

**Comment by wmmc88** [comment]
Using depth image to laserscan right. Check the Zed to see if there aren't already launch files setup for that

**Comment by wraftus** [comment]
yeah, the zed wrapper seems to just give a depth image
