### ISSUE TITLE
Generate preliminary URDF & motor/sensor config

### ISSUE THREAD

**Issue by Matthew-Reynolds** [uwreact/uwreact_robot#83]
# 🚀 Feature Request

Although the design of the robot is not complete, there is enough known about the system to create a rough URDF that should be accurate enough to get us off the ground to start some testing. Waiting on some critical dimensions from the mechanical team to finish up the URDF.

Camera and Zed placement is still unknown, but the actuators and their associated sensors, as well as some limit switches for game piece detection, are all defined enough that they can be worked into the model.

As more details from the mechanical team become available, I will update this issue accordingly to track the data I use to create the URDF.

**Comment by Matthew-Reynolds** [comment]
**Very rough** list of motors and sensors:

- 3 CIM/TalonSRX drivetrain (x2)
- 1 drivetrain encoder (VEX mag encoder?) (x2)
- 4 775Pro/TalonSRX elevator (1 master, 3 slave)
- 1 encoder for elevator (TODO: Add/replace w/ 10-turn pot)
- 1 BAG/TalonSRX for intake roller (No feedback)
- 1 775Pro/TalonSRX for intake wrist
- 1 absolute encoder (VEX mag) for intake wrist
- 1/2 CIM/TalonSRX for level-2-climb-stick?
- 1 10-turn pot for level-2-climb-stick?
- 2 pneumatic cylinders (double-valve sol?) for hatch grabber
- 2 pneumatic cylinders (single-valve sol?) for hatch pusher
- TODO: 2x lim switch for hatch (one L/R?)
- TODO: something for cargo detection

**Comment by wmmc88** [comment]
@Matthew-Reynolds any update on this?
